name: RandCustomizer
version: '${project.version}'
main: de.terrocraft.randcustomizer.RandCustomizer
api-version: '1.20.4'
description: This is a plugin for CityBuild servers with PlotSquared, allowing players to customize their roads around their plots.
authors:
  - Terrocraft
  - Schemil053
  - LevinGamer8
depend:
  - PlotSquared
  - WorldEdit
commands:
  randeditmode:
    description: Enables edit mode for customizing roads around plots.
    usage: /randeditmode
    permission: randcustomizer.randeditmode
permissions:
  randcustomizer.randeditmode:
    description: Allows using the /randeditmode command.
    default: op
  randcustomizer.randeditmode.bypass:
    description: Allows bypassing restrictions in edit mode.
    default: op
  randcustomizer.randeditmode.add:
    description: Allows adding blocks to edit mode.
    default: op
  randcustomizer.randeditmode.remove:
    description: Allows removing blocks in edit mode.
    default: op
  randcustomizer.randeditmode.reload:
    description: Allow to reload the plugin.
    default: op
